### ISSUE TITLE
FF-esr: add plasma desktop integration

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#17]
not sure if this is installed for esr

**Comment by ScarlettGatelyMoore** [comment]
The extension is installed, sadly p-b-i is broken in stable do to politics. I do however have a MR here to fix it https://salsa.debian.org/qt-kde-team/kde/plasma-browser-integration/merge_requests/3
maxy should approve it soon. But since we use stable I will need to bring my packaging to DCI to address this issue. Doing that now :)
