### ISSUE TITLE
installing Netrunner has partition read Netrunner 19.06 after install

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#48]
![Screenshot_20190817_131241](https://user-images.githubusercontent.com/840070/63211192-36798e80-c0f4-11e9-881b-c47e29742cb2.png)

**Comment by ScarlettGatelyMoore** [comment]
I have bashed my head on this one for hours now and I have reduced it to a problem with os-prober returning Netrunner 19.06 (19.06) Unfortunately, I cannot for the life of me figure out why, and where it gets that value. It is 8pm and I have been going since 2:45 this morning. I need to rest my brain. I will get back to it in the morning.

**Comment by llelectronics** [comment]
Short Idea run a grep -ri for 19.06 for /etc and see jf it comes up wjth anything.

**Comment by ScarlettGatelyMoore** [comment]
I did do that, and nothing.
What I have found this morning though is that this is only a problem when there is an existing partition with the broken lsb-release. I did a fresh install with an empty partition and it show Netrunner as expected. I am going to get some screenies and bug [ade], as I think this may be upstream.

**Comment by llelectronics** [comment]
It is normal that it reads the lsb-release of the already existing partition (this is what it shows by default). So if the lsb-release of the installed system shows 19.06 then it shows 19.06

**Comment by ScarlettGatelyMoore** [comment]
Ok, this was actually fixed with my update to lsb_release last night. Silly me forgot to select the partition to alter. Now the After correctly show netrunner.
![alongside](https://user-images.githubusercontent.com/1056501/63226002-04b40680-c18c-11e9-8677-8ef84a3ab387.png)
![erase](https://user-images.githubusercontent.com/1056501/63226003-08478d80-c18c-11e9-926a-326afaab6f1a.png)
![replace](https://user-images.githubusercontent.com/1056501/63226005-0b427e00-c18c-11e9-9b76-f7e5296d5b98.png)
